### ISSUE TITLE
8852be archlinux bluetooth see any peripheral

### ISSUE THREAD

**Issue by Mula-Gabriel** [lwfinger/rtw89-BT#10]
Hello,
My Bluetooth doesn't see any peripheral : 

I have an asus x670-P Wifi motherboard, look like it come with rtw8852be, i have installed the driver rtw89
The wifi works 
09:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. Device [10ec:b852]
	Subsystem: AzureWave Device [1a3b:5471]
	Kernel driver in use: rtw89_8852be
	Kernel modules: rtw_8852be

I am on archlinux-next.

The ble doesn't works, can't see any periphera
gaby@archlinux ~> lsusb
...
Bus 003 Device 002: ID 13d3:3571 IMC Networks Bluetooth Radio

gaby@archlinux ~> bluetoothctl scan on
Discovery started
[CHG] Controller E8:FB:1C:4D:69:F9 Discovering: yes
...

**Comment by lwfinger** [comment]
That BT device was unknown to me, and thus not in the tables. Do a git pull, make, sudo make install, and reboot. Do you get BT now?

**Comment by Mula-Gabriel** [comment]
No, same behavior 
PC can't see perih, and my smartphone can't see my PC (a device with a different mac that E8:FB:1C:4D:69:F9 appear, but can't be paire on my smartphone, not sure if it's related or not)

i have also try on current kernel

gaby@archlinux ~> uname -a
Linux archlinux 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux


gaby@archlinux ~> lsusb
Bus 009 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 010 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 008 Device 003: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub             
Bus 008 Device 002: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub             
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 004: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 007 Device 003: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub             
Bus 007 Device 002: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub             
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 004: ID 05e3:0749 Genesys Logic, Inc. SD Card Reader and Writer
Bus 006 Device 003: ID 05e3:0616 Genesys Logic, Inc. hub
Bus 006 Device 002: ID 05e3:0616 Genesys Logic, Inc. hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 003: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 005 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 0b05:19af ASUSTek Computer, Inc. AURA LED Controller
Bus 003 Device 002: ID 13d3:3571 IMC Networks Bluetooth Radio
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0b05:1835 ASUSTek Computer, Inc. Asus GK1100 Gaming Keyboard
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

gaby@archlinux ~> lspci -k -nn
00:00.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14d8]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
00:00.2 IOMMU [0806]: Advanced Micro Devices, Inc. [AMD] Device [1022:14d9]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
00:01.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14da]
00:01.2 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:14db]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: pcieport
00:02.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14da]
00:02.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:14db]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: pcieport
00:03.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14da]
00:04.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14da]
00:08.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14da]
00:08.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:14dd]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: pcieport
00:08.3 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:14dd]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: pcieport
00:14.0 SMBus [0c05]: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller [1022:790b] (rev 71)
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: piix4_smbus
	Kernel modules: i2c_piix4, sp5100_tco
00:14.3 ISA bridge [0601]: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge [1022:790e] (rev 51)
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
00:18.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e0]
00:18.1 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e1]
00:18.2 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e2]
00:18.3 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e3]
	Kernel driver in use: k10temp
	Kernel modules: k10temp
00:18.4 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e4]
00:18.5 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e5]
00:18.6 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e6]
00:18.7 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Device [1022:14e7]
01:00.0 Non-Volatile memory controller [0108]: Seagate Technology PLC FireCuda 530 SSD [1bb1:5018] (rev 01)
	Subsystem: Seagate Technology PLC FireCuda 530 SSD [1bb1:5018]
	Kernel driver in use: nvme
	Kernel modules: nvme
02:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f4] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
03:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
03:08.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
03:0c.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
03:0d.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
05:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f4] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
06:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
06:04.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
06:05.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
06:08.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
06:0c.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
06:0d.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f5] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:3328]
	Kernel driver in use: pcieport
08:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller [10ec:8125] (rev 05)
	Subsystem: ASUSTeK Computer Inc. Device [1043:87d7]
	Kernel driver in use: r8169
	Kernel modules: r8169
09:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. Device [10ec:b852]
	Subsystem: AzureWave Device [1a3b:5471]
	Kernel driver in use: rtw89_8852be
	Kernel modules: rtw_8852be
0b:00.0 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f7] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:1142]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
0c:00.0 SATA controller [0106]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f6] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:1062]
	Kernel driver in use: ahci
0d:00.0 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f7] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:1142]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
0e:00.0 SATA controller [0106]: Advanced Micro Devices, Inc. [AMD] Device [1022:43f6] (rev 01)
	Subsystem: ASMedia Technology Inc. Device [1b21:1062]
	Kernel driver in use: ahci
0f:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c2)
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
0f:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller [1002:1640]
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller [1002:1640]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
0f:00.2 Encryption controller [1080]: Advanced Micro Devices, Inc. [AMD] VanGogh PSP/CCP [1022:1649]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: ccp
	Kernel modules: ccp
0f:00.3 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:15b6]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
0f:00.4 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:15b7]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
0f:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
	DeviceName: Realtek ALC1220
	Subsystem: ASUSTeK Computer Inc. Device [1043:87fb]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
10:00.0 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Device [1022:15b8]
	Subsystem: ASUSTeK Computer Inc. Device [1043:8877]
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci

**Comment by Mula-Gabriel** [comment]
I have try the following to give you some info :
On one terminal :
gaby@archlinux ~ [1]> bluetoothctl scan on
Discovery started
[CHG] Controller E8:FB:1C:4D:69:F9 Discovering: yes
^C⏎                                                                                                                   gaby@archlinux ~> bluetoothctl scan on
Discovery started
[CHG] Controller E8:FB:1C:4D:69:F9 Discovering: yes
^C⏎                                                                                                                   gaby@archlinux ~> 

On a another one : 
gaby@archlinux ~> sudo btmon
Bluetooth monitor ver 5.65
= Note: Linux version 6.0.2-arch1-1 (x86_64)                                                                 0.504227
= Note: Bluetooth subsystem version 2.22                                                                     0.504229
= New Index: E8:FB:1C:4D:69:F9 (Primary,USB,hci0)                                                     [hci0] 0.504230
= Open Index: E8:FB:1C:4D:69:F9                                                                       [hci0] 0.504230
= Index Info: E8:FB:1C:4D:69:F9 (Realtek Semiconductor Corporation)                                   [hci0] 0.504230
@ MGMT Open: bluetoothd (privileged) version 1.22                                                   {0x0001} 0.504231
> HCI Event: Inquiry Complete (0x01) plen 1                                                        #1 [hci0] 3.739259
        Status: Success (0x00)
@ MGMT Event: Discovering (0x0013) plen 2                                                    {0x0001} [hci0] 3.739305
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
        Discovery: Disabled (0x00)
@ MGMT Command: Start Discovery (0x0023) plen 1                                              {0x0001} [hci0] 9.167169
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
< HCI Command: LE Set Random Address (0x08|0x0005) plen 6                                          #2 [hci0] 9.167246
        Address: 10:EC:DA:32:63:F5 (Non-Resolvable)
> HCI Event: Command Complete (0x0e) plen 4                                                        #3 [hci0] 9.281177
      LE Set Random Address (0x08|0x0005) ncmd 2
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Parameters (0x08|0x0041) plen 8                                #4 [hci0] 9.281254
        Own address type: Random (0x01)
        Filter policy: Accept all advertisement (0x00)
        PHYs: 0x01
        Entry 0: LE 1M
          Type: Active (0x01)
          Interval: 11.250 msec (0x0012)
          Window: 11.250 msec (0x0012)
> HCI Event: Command Complete (0x0e) plen 4                                                        #5 [hci0] 9.284178
      LE Set Extended Scan Parameters (0x08|0x0041) ncmd 2
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                                    #6 [hci0] 9.284251
        Extended scan: Enabled (0x01)
        Filter duplicates: Enabled (0x01)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                                        #7 [hci0] 9.289176
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 2
        Status: Success (0x00)
@ MGMT Event: Command Complete (0x0001) plen 4                                               {0x0001} [hci0] 9.289236
      Start Discovery (0x0023) plen 1
        Status: Success (0x00)
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
@ MGMT Event: Discovering (0x0013) plen 2                                                    {0x0001} [hci0] 9.289244
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
        Discovery: Enabled (0x01)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                                   #8 [hci0] 14.417664
        Extended scan: Disabled (0x00)
        Filter duplicates: Disabled (0x00)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                                       #9 [hci0] 14.534103
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 2
        Status: Success (0x00)
< HCI Command: Inquiry (0x01|0x0001) plen 5                                                      #10 [hci0] 14.534164
        Access code: 0x9e8b33 (General Inquiry)
        Length: 5.12s (0x04)
        Num responses: 0
> HCI Event: Command Status (0x0f) plen 4                                                        #11 [hci0] 14.537104
      Inquiry (0x01|0x0001) ncmd 2
        Status: Success (0x00)
> HCI Event: Inquiry Complete (0x01) plen 1                                                      #12 [hci0] 19.739034
        Status: Success (0x00)
@ MGMT Event: Discovering (0x0013) plen 2                                                   {0x0001} [hci0] 19.739072
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
        Discovery: Disabled (0x00)
@ MGMT Command: Start Discovery (0x0023) plen 1                                             {0x0001} [hci0] 25.673750
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
< HCI Command: LE Set Random Address (0x08|0x0005) plen 6                                        #13 [hci0] 25.673795
        Address: 0A:C5:8E:47:D7:B8 (Non-Resolvable)
> HCI Event: Command Complete (0x0e) plen 4                                                      #14 [hci0] 25.787947
      LE Set Random Address (0x08|0x0005) ncmd 2
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Parameters (0x08|0x0041) plen 8                              #15 [hci0] 25.788021
        Own address type: Random (0x01)
        Filter policy: Accept all advertisement (0x00)
        PHYs: 0x01
        Entry 0: LE 1M
          Type: Active (0x01)
          Interval: 11.250 msec (0x0012)
          Window: 11.250 msec (0x0012)
> HCI Event: Command Complete (0x0e) plen 4                                                      #16 [hci0] 25.790936
      LE Set Extended Scan Parameters (0x08|0x0041) ncmd 2
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                                  #17 [hci0] 25.790991
        Extended scan: Enabled (0x01)
        Filter duplicates: Enabled (0x01)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                                      #18 [hci0] 25.795936
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 2
        Status: Success (0x00)
@ MGMT Event: Command Complete (0x0001) plen 4                                              {0x0001} [hci0] 25.795983
      Start Discovery (0x0023) plen 1
        Status: Success (0x00)
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
@ MGMT Event: Discovering (0x0013) plen 2                                                   {0x0001} [hci0] 25.795990
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
        Discovery: Enabled (0x01)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                                  #19 [hci0] 31.057669
        Extended scan: Disabled (0x00)
        Filter duplicates: Disabled (0x00)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                                      #20 [hci0] 31.174309
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 2
        Status: Success (0x00)
< HCI Command: Inquiry (0x01|0x0001) plen 5                                                      #21 [hci0] 31.174377
        Access code: 0x9e8b33 (General Inquiry)
        Length: 5.12s (0x04)
        Num responses: 0
> HCI Event: Command Status (0x0f) plen 4                                                        #22 [hci0] 31.176877
      Inquiry (0x01|0x0001) ncmd 2
        Status: Success (0x00)
> HCI Event: Inquiry Complete (0x01) plen 1                                                      #23 [hci0] 36.378800
        Status: Success (0x00)
@ MGMT Event: Discovering (0x0013) plen 2                                                   {0x0001} [hci0] 36.378845
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
        Discovery: Disabled (0x00)
@ MGMT Command: Start Discovery (0x0023) plen 1                                             {0x0001} [hci0] 41.165829
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
< HCI Command: LE Set Random Address (0x08|0x0005) plen 6                                        #24 [hci0] 41.165906
        Address: 19:89:C2:91:5F:74 (Non-Resolvable)
> HCI Event: Command Complete (0x0e) plen 4                                                      #25 [hci0] 41.280723
      LE Set Random Address (0x08|0x0005) ncmd 2
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Parameters (0x08|0x0041) plen 8                              #26 [hci0] 41.280778
        Own address type: Random (0x01)
        Filter policy: Accept all advertisement (0x00)
        PHYs: 0x01
        Entry 0: LE 1M
          Type: Active (0x01)
          Interval: 11.250 msec (0x0012)
          Window: 11.250 msec (0x0012)
> HCI Event: Command Complete (0x0e) plen 4                                                      #27 [hci0] 41.283720
      LE Set Extended Scan Parameters (0x08|0x0041) ncmd 2
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                                  #28 [hci0] 41.283783
        Extended scan: Enabled (0x01)
        Filter duplicates: Enabled (0x01)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                                      #29 [hci0] 41.288718
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 2
        Status: Success (0x00)
@ MGMT Event: Command Complete (0x0001) plen 4                                              {0x0001} [hci0] 41.288770
      Start Discovery (0x0023) plen 1
        Status: Success (0x00)
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
@ MGMT Event: Discovering (0x0013) plen 2                                                   {0x0001} [hci0] 41.288777
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
        Discovery: Enabled (0x01)
@ MGMT Command: Stop Discovery (0x0024) plen 1                                              {0x0001} [hci0] 45.181381
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                                  #30 [hci0] 45.181413
        Extended scan: Disabled (0x00)
        Filter duplicates: Disabled (0x00)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                                      #31 [hci0] 45.297675
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 2
        Status: Success (0x00)
@ MGMT Event: Command Complete (0x0001) plen 4                                              {0x0001} [hci0] 45.297743
      Stop Discovery (0x0024) plen 1
        Status: Success (0x00)
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
@ MGMT Event: Discovering (0x0013) plen 2                                                   {0x0001} [hci0] 45.297755
        Address type: 0x07
          BR/EDR
          LE Public
          LE Random
        Discovery: Disabled (0x00)

**Comment by Mula-Gabriel** [comment]
i have tried to start the bluetooth service with '-d' option, then output journalctl in that file :

[bluetoothd.txt](https://github.com/lwfinger/rtw89-BT/files/10046940/bluetoothd.txt)

the service is stuck in a Start/STOP loop.

I have tried to contact Bluetooth mailing list, i did get any answer, do you know someone i can write to to move on that bug ?

**Comment by Mula-Gabriel** [comment]
Good surprise, after update my system, the Bluetooth works.

**Comment by Lojcs** [comment]
I have the same issue. Did it break again after another update for you?

**Comment by lwfinger** [comment]
What is the output of 'lsusb' that pertains to your Bluetooth device?

**Comment by Lojcs** [comment]
`us 004 Device 002: ID 13d3:3571 IMC Networks Bluetooth Radio`

**Comment by rklxmok** [comment]
I have the same issue on Nobara/fedora 37, kernel-6.2.6-201.fsync.fc37. 
--- Bus 002 Device 002: ID 13d3:3571 IMC Networks Bluetooth Radio ---
I am using the asus b650m motherboard, this is the onboard radio. The wifi was also completely inoperable until I loaded your drivers from the repo https://github.com/lwfinger/rtw89

I even tried removing the driver and installing the broadcom package, but it behaves identically as the drivers in your repo

**Comment by Mula-Gabriel** [comment]
Just a message to says it's still broken (Linux archlinux 6.3.5-arch1-1)

lwfinger, maybe you know someone i can write too ?

Opened thread on forum :
https://forums.archlinux.fr/viewtopic.php?t=22827
https://bbs.archlinux.org/viewtopic.php?id=285721

**Comment by Mula-Gabriel** [comment]
kernel 6.4 fixed it.
