### ISSUE TITLE
Installation failed "cannot stat '*.bin'"

### ISSUE THREAD

**Issue by Robonics** [lwfinger/rtw89-BT#17]
When running `make sign-install`, it fails saying `cannot stat '*.bin' no such file or directory`, and indeed looking through the files, there are no `bin` files.

I'm on Linux Mint (Ubuntu/Debian Based) 21, Kernel Version 5.15.0-72-generic

**Comment by lwfinger** [comment]
The firmware is no longer in the repo. It is too much hassle to keep it updated. Your distro should be including it anyway.

The problem with install has been fixed.
