### ISSUE TITLE
Bluetooth stutters when wifi is enabled

### ISSUE THREAD

**Issue by marco-calautti** [lwfinger/rtw89-BT#20]
To be honest, I do not know whether the issues is on the bluetooth driver here or on the Kernel's wifi driver. Anyway, when both wifi and Bluetooth are enabled, Bluetooth stutters and lags (e.g., headphones have stuttering audio, or bluetooth game controller misses inputs).

Before you ask, my Wifi is connected to a 5Ghz wifi, so there should not be interferences.

**Comment by lwfinger** [comment]
The 2.4 GHz and 5 GHz radios share a lot of components, thus actions on BT in the 2.4 GHz band affect wifi on the 5 GHz band, and vice-versa.

Yours is a well-known problem that has been discussed a lot. As root, create a file /usr/lib/modprobe.d and add the following lines:
options rtw89_core disable_ps_mode=y
options rtw89core disable_ps_mode=y

This change will decrease your battery life, but will eliminate the BT interference.

**Comment by lwfinger** [comment]
Firmware version 0.29.29.5 for the rtw89_8852BE has been released to fix this problem. You can get it from https://www.lwfinger.com/donloads/. You need the version where the file name ends in -1.
