### ISSUE TITLE
Ubuntu 6.5 Build Errors

### ISSUE THREAD

**Issue by JacobWurtz** [lwfinger/rtw89-BT#23]
I'm seeing the following build errors when attempting to make:
![Screenshot from 2024-01-16 08-51-21](https://github.com/lwfinger/rtw89-BT/assets/12007781/5cfe7e9b-3adb-4627-9dab-633557124db8)

Output from lsusb:
![Screenshot from 2024-01-16 08-51-45](https://github.com/lwfinger/rtw89-BT/assets/12007781/53003e93-2f94-431b-99de-5c9bd402beb0)

Installed firmware:
![Screenshot from 2024-01-16 08-53-42](https://github.com/lwfinger/rtw89-BT/assets/12007781/6cc54672-d91c-4a6d-9818-a7fd1c5f7783)

Output from uname -r (ubuntu 22.04):
![Screenshot from 2024-01-16 08-52-53](https://github.com/lwfinger/rtw89-BT/assets/12007781/7344565f-e3dd-4eb2-8142-8c9b3c3a2e46)

Looks like some of the files are correctly compiling, but it's choking on at least one.

For more context, the issue I'm facing is non-functional bluetooth on a tp link network card. The bluetooth is "on", but can't actually detect or connect to anything. I'm hoping that this driver will do the trick (rtw89 worked beautifully for my network card), as long as I can get it to compile.

**Comment by JacobWurtz** [comment]
As a side note, thank you very much for owning and maintaining this repo. This is really fantastic work!

**Comment by lwfinger** [comment]
This problem was a bit trickier than most. On my system, the missing globals were being loaded from the underlying kernel, thus no error. Do a 'giit pull' and report back.

**Comment by JacobWurtz** [comment]
Progress, but not quite there yet.
![Screenshot from 2024-01-16 11-12-36](https://github.com/lwfinger/rtw89-BT/assets/12007781/20828eaa-1d04-4d3c-988a-7278d86c1614)

Thank you for the quick response. Let me know if I can provide anything else to help narrow it down.

**Comment by lwfinger** [comment]
Try again. I made another fix.

**Comment by JacobWurtz** [comment]
That did the trick. Not only did the build work, but it has solved my bluetooth issue.

Thank you so much for all your help! You're doing fantastic work out here.
